CREATE TABLE [dbo].[master_institute] (
    [InstituteId]             INT             NOT NULL,
    [NodalOfficeId]           INT             NULL,
    [InstituteCode]           NVARCHAR (50)   NULL,
    [InstituteName]           VARCHAR (500)   NULL,
    [Address]                 NVARCHAR (500)  NULL,
    [Address1]                NVARCHAR (500)  NULL,
    [DistrictCode]            INT             NULL,
    [CityId]                  INT             NULL,
    [PINCODE]                 VARCHAR (10)    NULL,
    [ContactNumber1]          VARCHAR (20)    NULL,
    [ContactNumber2]          VARCHAR (20)    NULL,
    [PublicContactNumber]     VARCHAR (20)    NULL,
    [EmailId]                 VARCHAR (100)   NULL,
    [Description]             NVARCHAR (1000) NULL,
    [Active]                  CHAR (1)        NULL,
    [LanguageId]              INT             NOT NULL,
    [Type]                    CHAR (3)        NULL,
    [AllottedCategory]        CHAR (1)        NULL,
    [ISPPP]                   CHAR (1)        NULL,
    [PPPApprovedOn]           NVARCHAR (20)   NULL,
    [Divisionid]              INT             NULL,
    [IsRemand]                CHAR (1)        NULL,
    [TalukCode]               INT             NULL,
    [PrincipalName]           VARCHAR (50)    NULL,
    [MobileNumber]            VARCHAR (13)    NULL,
    [WebAddress]              VARCHAR (100)   NULL,
    [TypeId]                  INT             NULL,
    [InstituteCodeId]         VARCHAR (4)     NULL,
    [ApplicationSubmitStatus] CHAR (1)        NULL,
    [Latitude]                VARCHAR (20)    NULL,
    [Longitude]               VARCHAR (20)    NULL,
    [LandlineNum]             VARCHAR (20)    NULL,
    [flagfreze]               VARCHAR (20)    NULL
);

